# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e530e866c5103f3ae6cf5e4fd7044ce43244f1ca2b70c10c9d327bfbe72dc77f01a0ccbe01fb41504fa932b6f926c7f57fe04f3ecdfbc0f0c4d37640b8031b4d

test:
  secret_key_base: 6913f987bf82456412c12a216def0bff50792f0d453c86b82f20ab0fb87b2ae3b575c759fce7fbceb7ce93b720da13b3f1d32e9ace219d5be9aa926aae0af524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
